### ISSUE TITLE
Clarification in C4 Graceful Error Handling

### ISSUE THREAD

**Issue by knightpp** [richardanaya/tour_of_rust#106]
[Graceful Error Handling](https://tourofrust.com/38_en.html)
This block of code 
 ```rust
match do_something_that_might_fail() {
    Ok(v) => v,
    Err(e) => e,
}
```
should be
 ```rust
match do_something_that_might_fail() {
    Ok(v) => v,
    Err(e) => return Err(e),
}
```
because the page tells that it equivalent to `do_something_that_might_fail()?`

> `?` operator ... If the Option type has None value or the Result type has Err value, return them immediately to the caller of the function.

**Comment by richardanaya** [comment]
Thanks! Fixing

**Comment by richardanaya** [comment]
Fixed on all languages
