### ISSUE TITLE
[WASM] chapter 1:  typo in css styles font-family

### ISSUE THREAD

**Issue by VincentFoulon80** [richardanaya/tour_of_rust#128]
On `main.html`, the font-family displayed in the header is "san-serif" instead of "sans-serif"

Seen on FR and EN translations for "1+1", "Importing Functions", "Logging Text". Maybe beyond these.
I didn't verified for other translations but we need to check and fix them.

**Comment by richardanaya** [comment]
Hmm, weird, I can't find this issue :) do you have a screenshot where you see it?

**Comment by VincentFoulon80** [comment]
on [this wasm studio link](https://webassembly.studio/?embed&f=jg96xg1ovj) from [this line](https://github.com/richardanaya/tour_of_rust/blob/master/wasm.yaml#L441) :
- open main.html
- check the `style` tag, there is `font-family: san-serif;`

![image](https://user-images.githubusercontent.com/26797476/84912122-59c8ed80-b0b9-11ea-840b-1b6f7b2ebd47.png)

**Comment by richardanaya** [comment]
ahh, gotcha ... that's actually a bug I can't fix :/ it's a bug over on Web Assembly studio side

**Comment by VincentFoulon80** [comment]
Oh I thought that was something related to our side. Okay I think we can redirect this issue (if not already opened) on WASM Studio and close this one.

**Comment by richardanaya** [comment]
https://github.com/wasdk/WebAssemblyStudio/issues/459
