### ISSUE TITLE
format code according to rust style

### ISSUE THREAD

**Issue by pickfire** [richardanaya/tour_of_rust#130]
Run rustfmt through the code, 4 spaces, 100 chars width, there should also be space in between parenthesis and curly braces. This allow more consistency with other rust code and easier to read.

https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md

**Comment by richardanaya** [comment]
I think i'm just using the rustfmt tool in Rust playground and whatever settings it uses.

**Comment by pickfire** [comment]
Yes, those are fine. But most of the code not from the playground have a different style. Example:

https://github.com/richardanaya/tour_of_rust/blob/c934b74919c75f03a5653e38a9cf35445be8a94d/lessons.yaml#L3423-L3428

**Comment by richardanaya** [comment]
Oh! Good point

**Comment by pickfire** [comment]
Let me fix this.

**Comment by richardanaya** [comment]
Welcome to the team!

**Comment by pickfire** [comment]
I feel bad looking at the state of the docs, the unformated code demotivates me. Still, I would like to shorten the zh part a bit, although I can't translate one myself.
