### ISSUE TITLE
Is there a example of a native librairy to help creating bindings with JavaScript?

### ISSUE THREAD

**Issue by mgemard** [richardanaya/tour_of_rust#131]
In `[Why Dynamic Invocation?](https://tourofrust.com/webassembly/19_en.html)`

It is said:

```
Most people come to WebAssembly to escape JavaScript. Dynamic creation of JavaScript functions allow us to use
libraries in our native language that do the hard part of dynamically creating their bindings without everyone having
to recreate the wheel.
```

I think we should give an example of such a library (for both Rust and C). Anyone know one of them?

**Comment by richardanaya** [comment]
I write one :P https://github.com/richardanaya/ramen , but I didn't feel like injecting my own library into a tutorial.

**Comment by mgemard** [comment]
It really did sound like you wanted to tell us what that library was :)

Since it does not seems to be very popular at the moment I think we can keep it like that.

But if your library or another one become popular it would be good to include it here like you did for wasm-bindgen.
