### ISSUE TITLE
Clarification in C.5 Dereferencing

### ISSUE THREAD

**Issue by knightpp** [richardanaya/tour_of_rust#151]
Currently, [the page](https://tourofrust.com/50_en.html) states as follows
> Using references, you can set the owner's value using the * operator.

I think it needs some clarity

> Using `&mut` references, you can set the owner's value using the `*` operator.

**Comment by richardanaya** [comment]
Good call!

**Comment by richardanaya** [comment]
Fixed in all languages and published
