### ISSUE TITLE
Chapter 9 Final Chapter!

### ISSUE THREAD

**Issue by richardanaya** [richardanaya/tour_of_rust#153]
Well, it's finally here! I'm not going to announce this final chapter this weekend.  I want to give our awesome french translators time to make it into the big announcement.  In the meantime, I will be spending time looking over the full content for minor corrections.  The end is in sight!

https://tourofrust.com/beta_chapter_9_en.html

**Comment by richardanaya** [comment]
@jassler @Dhghomon @knightpp @albatraduce @Denstone @mgemard @spartucus @simeg

**Comment by sbechet** [comment]
idea:

- explain `rustup` what can be done with it (ex. `rustup doc` for offline documentation)
- explain `cargo`: `build`, `run`, --release, target/{debug, release} dir to find binary, `doc --open`
