### ISSUE TITLE
Left and right arrows to change page does not work if there is a playground on the page

### ISSUE THREAD

**Issue by mgemard** [richardanaya/tour_of_rust#155]
I do not know if anyone has the same problem but I cannot go to previous/next page if there is a Rust playground on the page.

Once the playground is loaded, it get the focus and right/left arrows can only be used to navigate in the code.

Can't we just not focus on the playground when we load the page?

**Comment by richardanaya** [comment]
There's some annoying issue with the Rust playground stealing focus I don't have control over (or know of a technique!). Let me see if I can do something hacky to help out.

**Comment by richardanaya** [comment]
I made a change, can you let me know how it feels? :)

**Comment by mgemard** [comment]
It feels like a hack.

The playground can still get the focus if you press `<-` or `->` at the right (or should I say wrong) moment.

**Comment by mgemard** [comment]
I don't see other solutions.

**Comment by richardanaya** [comment]
we've done our best!
