### ISSUE TITLE
Displaying error messages if Rust Playground is blocked?

### ISSUE THREAD

**Issue by matthewkmayer** [richardanaya/tour_of_rust#19]
First, thanks for your efforts on Tour of Rust: I'm glad to see such a project as it will certainly help people get started with Rust. 👍 

When I visited the site when the first chapter was announced, only the left side rendered and the playground didn't show up. It gave the appearance of being broken and hid all the hard work done for the project.

I'm using Firefox with the Privacy Badger extension and it blocked the playground. Is it possible to show a placeholder to help make it clear the playground should load on the right side of the screen?

Screenshot example from today:

<img width="1280" alt="Screen Shot 2020-05-09 at 3 26 00 PM" src="https://user-images.githubusercontent.com/4998189/81486499-04700580-920a-11ea-9c74-4c0f53c98434.png">

Thanks again for your work on this!

**Comment by richardanaya** [comment]
Thanks for the heads up.  Do you happen to know if there's a html/css standard for how to do placeholders for compatibility with privacy extensions like this. Maybe you have a link to a website that does it right?

**Comment by matthewkmayer** [comment]
I'm not sure if there is a standardized way of handling this scenario. Frontend work is outside my wheelhouse. 😄 

Maybe an FAQ or troubleshooting page on the site would be enough. "Site should look like [screenshot showing playground on the right]. If it doesn't, check if your browser/network/whatever is blocking the Rust Playground."

Also, I submitted a report of "Privacy Badger broke this site" to EFF via the Privacy Badger feedback form, perhaps there is something they can do on their end. Not sure where that report ends up though.
