### ISSUE TITLE
Split the giant Markdown file

### ISSUE THREAD

**Issue by tobiasvl** [richardanaya/tour_of_rust#193]
Having every chapter, in every language, in one large Markdown file makes it awkward to submit pull requests.

**Comment by raminos** [comment]
Maybe a chapter based approach? That would make splitting up easier.

**Comment by knightpp** [comment]
The way I see it. There are `english` and `translations` folders. In `translations` we put a copy of `english` folder, but renaming to lang code. For every chapter, we have one folder that contains one source file of that page. When generating `.html`, the generator must parse every folder as one chapter in order of the first number in the name. According to said, every source file would have the following structure.
```
title: ...
code: ... // optional for translations
content_markdown: |
	Content ...
```

```
.
├── english
│   ├── 0 - common_words.txt
│   ├── 1 - Chapter 1
│   │   ├── 1 - First page of Chapter 1.txt
│   │   └── 2 - Second page of Chapter 1.txt
│   └── 2 - Chapter 2
└── translations
    └── fr
        ├── 0 - common_words.txt
        ├── 1 - Chapter 1
        │   ├── 1 - First page of Chapter 1.txt
        │   └── 2 - Second page of Chapter 1.txt
        └── 2 - Chapter 2
```

**Comment by Nemin32** [comment]
This would absolutely be a nice thing to have. It is kind of hard to properly navigate such a huge file and could easily be intimidating for some who are interested in contributing

**Comment by richardanaya** [comment]
Hey everyone, appreciate all the feedback, i'm going to make this a priority this week.

**Comment by richardanaya** [comment]
Hey all, I split the markdown this morning. I need some time to update the generator but hopefully will make lives easier for everyone.

**Comment by tobiasvl** [comment]
Very nice! Just a heads up, @richardanaya, it seems you've made some commits with an email address that isn't connected to your github account.

**Comment by raminos** [comment]
@richardanaya I think we can close this issue now

**Comment by richardanaya** [comment]
generator has been updates to the new structure
