### ISSUE TITLE
Hi! translate to Korean

### ISSUE THREAD

**Issue by fermat39** [richardanaya/tour_of_rust#199]
Hi! 

I want to translate to Korean

**Comment by richardanaya** [comment]
Awesome!

**Comment by richardanaya** [comment]
@Dhghomon

**Comment by fermat39** [comment]
How can I start?

**Comment by richardanaya** [comment]
You should only have to edit https://github.com/richardanaya/tour_of_rust/blob/master/lessons.yaml :)

the korean language code is "ko"

perhaps start with translating common words

and a few pages in chapter 1? Just make a PR and I will merge it!

welcome to the team!

**Comment by fermat39** [comment]
Thank you

**Comment by Dhghomon** [comment]
@fermat39  Awesome! 도움이 필요하시면 도와드릴게요.

**Comment by fermat39** [comment]
@Dhghomon 감사합니다. 같은 서울에 계시면 뵈요~~~

**Comment by Dhghomon** [comment]
@fermat39 네 같은 서울에 살고있고 한국어 러스트 Discord 회원이기도 해요! 거기서도 제가 Dhghomon입니다

**Comment by richardanaya** [comment]
Hey all, just wanted to notify this issue watcher that there's been a significant change to the yaml structure.  `lessons.yaml` has been broken up into chapters by language in the `lessons` folder.  If you have a PR in motion, don't worry I will merge it in.  If starting on something new, try to use the new structure. Thank you :pray:  :)

**Comment by fermat39** [comment]
Thanks
-----Original Message-----

**Comment by jenix21** [comment]
@fermat39 @Dhghomon
Hello, I hope to join this issue. :D
