### ISSUE TITLE
Translation to Hungarian

### ISSUE THREAD

**Issue by Nemin32** [richardanaya/tour_of_rust#215]
Apologies, I only saw that you also need to make an issue after I opened #214 . Well anyway, most details are in the pull request, but the gist of it is that I wish to start translating this project in my language.

**Comment by richardanaya** [comment]
No need for issue. Appreciate the translation! Let me see what I can do for
you on the font issue :)

**Comment by richardanaya** [comment]
Welcome to the team!

**Comment by richardanaya** [comment]
Hey all, just wanted to notify this issue watcher that there's been a significant change to the yaml structure.  `lessons.yaml` has been broken up into chapters by language in the `lessons` folder.  If you have a PR in motion, don't worry I will merge it in.  If starting on something new, try to use the new structure. Thank you :pray:  :)

**Comment by Nemin32** [comment]
Thanks for the heads up. My newest pull request is following the new format.

**Comment by richardanaya** [comment]
@Nemin32 can you check out the hungarian on https://tourofrust.com/00_hu.html and it's pages.  I switched to using a hopefully more internationalized font.  Let me know what you think.

**Comment by Nemin32** [comment]
If you're happy with it, I'm too. All characters render just fine now.
