### ISSUE TITLE
Suggestion: use page down/page up to change to the next/previous page

### ISSUE THREAD

**Issue by mgemard** [richardanaya/tour_of_rust#218]
ToG always uses page down/page up to change to the next/previous pages, and immediately focuses in the editor. ToR's use of left/right arrows means one needs to click to focus the editor/content depending on what one wants to navigate

from [reddit feedback](https://www.reddit.com/r/rust/comments/hpt01d/tour_of_rust/fxuddcb?utm_source=share&utm_medium=web2x)

That way we could keep the focus on the editor and still use page up/down keys to navigate. We will probably need to revert [this commit](https://github.com/richardanaya/tour_of_rust/commit/693fce41ba6d3bcf1206e3e7ffdfd3bfd9bde942).

**Comment by richardanaya** [comment]
I'm really curious if other people find this is desired behavior. I'm not sure what percentage of ToR visitors are:
* pure readers who never modify the code
* always want to play with the code

**Comment by richardanaya** [comment]
I feel like we have less control over our editor than Tour of Go, and I personally think left right arrows are more intuitive navigation. Closing this.
