### ISSUE TITLE
Suggestion: preserves the content of the edits made to the editors even when the page

### ISSUE THREAD

**Issue by mgemard** [richardanaya/tour_of_rust#219]
ToG preserves the content of the edits made to the editors even when the page we're on changes (and has an explicit reset button). ToR reloads the editor with the original content if you switch from one page to another.

from [reddit feedback](https://www.reddit.com/r/rust/comments/hpt01d/tour_of_rust/fxuddcb?utm_source=share&utm_medium=web2x)

Would it be possible to do something like this?

**Comment by richardanaya** [comment]
Appreciate you gathering this stuff @mgemard ,  as per this particular issue the playground editor Tour of Rust uses is in an iframe.   We don't really have control over it's behavior and I don't think we can modify it due to cross-domain javascript issues.
