### ISSUE TITLE
Explaining Rustacean

### ISSUE THREAD

**Issue by Nemin32** [richardanaya/tour_of_rust#228]
In Chapter 4, where the usage of unwrap is discussed, the reader is called rustacean. To a newcomer the name might look a bit weird, even if they can make out that it's a portmanteau. I recommend either briefly talking about Rust's "culture" and community in the beginning or including a footnote under the aforementioned section explaining the word.

**Comment by richardanaya** [comment]
Great idea!

**Comment by Zerotask** [comment]
I would introduce it at the beginning, in the same lesson Ferris is introduced
