### ISSUE TITLE
Remove cosmetic whitespace from Markdown

### ISSUE THREAD

**Issue by tobiasvl** [richardanaya/tour_of_rust#229]
The Markdown documents are split into short lines (perhaps an attempt at 80 character lines?).

This might be nice for people with editors that don't wrap, but not nice for people who want to contribute since it makes it hard to search for strings in the files (because the sentence you're looking for might have a linebreak in the middle of it, and indentation at the beginning of the next line as well). 

I ran into this multiple times when I recently corrected a bunch of typos that I found while going through the ToR in my browser - when I went looking for those sentences in the source code, I often had to search by regex.

**Comment by richardanaya** [comment]
Interesting! Thanks for the heads up, sounds like a good plan. I need to improve the whitespace anyways in the new structure since the yaml parser messed a lot of things up.
