### ISSUE TITLE
WebAssembly spelling

### ISSUE THREAD

**Issue by OAyomide** [richardanaya/tour_of_rust#234]
I believe the right way to spell WebAssembly is as it is, not Web Assembly (two words).

I have a PR drafted to fix this and I'd submit if you dont mind.

**Comment by richardanaya** [comment]
Awesome! yah WebAssembly is the right spelling :P I always forget that weirdness

**Comment by OAyomide** [comment]
Sweet!! #236 should take care of it.

If there's another wrong occurrence i see, i'll fix. Do you mind if I close the issue now?

**Comment by richardanaya** [comment]
thank you!
