### ISSUE TITLE
Ch. 5 code example is wrong on drop order

### ISSUE THREAD

**Issue by MatthijsBlom** [richardanaya/tour_of_rust#253]
The current code example on [page 44](https://tourofrust.com/44_en.html) reads
```rust
struct Foo {
    x: i32,
}

fn main() {
    let foo_a = Foo { x: 42 };
    let foo_b = Foo { x: 13 };

    println!("{}", foo_a.x);
    // foo_a is dropped here because it's no longer
    // used to after this location

    println!("{}", foo_b.x);
    // foo_b is dropped here because of the end
    // of the function scope
}
```
and suggests that the variables `foo_a` and `foo_b` are dropped in the order in which they were defined (at least in this case). However, an explicit `Drop` implementation à la
```rust
impl Drop for Foo {
    fn drop(&mut self) {
        println!("Dropping {}", self.x);
    }
}
```
makes clear that this is not te case: variables are in fact dropped in reverse declaration order (as is [documented in the reference](https://doc.rust-lang.org/reference/destructors.html#drop-scopes)).

---

I'm not yet _entirely_ sure how to fix this. Simply replacing the mistaken commentary with correct commentary, alongside the observation that dropping by reverse declaration order makes intuitive sense because later variables may depend on earlier ones, will go a long way, but there are some hairy cases:

-    the presence of function calls that consume variables;
-    the difference between declaration order and initialization order.

I may follow up on this when I have finished the book and investigated some more.

**Comment by richardanaya** [comment]
Thanks for bringing this up, I put some rewriting in a207ed028d27d3b302eb5fc34d2b19a6a54d47b2
