### ISSUE TITLE
Q: How do you keep the translation up to date?

### ISSUE THREAD

**Issue by rafedramzi** [richardanaya/tour_of_rust#265]
Hi Folks, I'd like to contribute by starting translation for bahasa Indonesia (id), I've translated the chapter 0 and common_words but before I do the rest of it, I want to ask you guys, how do you keep the translation up to date? Assuming the English translation is the source of truth, do you guys have mechanism to tell the rest of the language if the English version changed?

**Comment by richardanaya** [comment]
Right now the English is changing very very little.

But if it does I’ll add it to the bottom of lessons/README.md
