### ISSUE TITLE
Proposal: Get rid of the 80 characters limit

### ISSUE THREAD

**Issue by rafedramzi** [richardanaya/tour_of_rust#268]
I noticed that all the texts is in 80-character limit mode, it makes me harder to translate since I have to make sure that the text within the 80-chars limit, it would be nice if we can get rid of it and use CSS property `word-wrap: break-word;` for in order to wrap the text.

**Comment by richardanaya** [comment]
Feel free to ignore that 80 character limit.  We transitioned  the structure of our yaml not too long ago, and unfortunately the parser was not that good and sort of messed up formatting of many areas :)
