### ISSUE TITLE
New Page - Calling Methods

### ISSUE THREAD

**Issue by richardanaya** [richardanaya/tour_of_rust#36]
Realized we probably need this page :)

https://tourofrust.com/beta_25_en.html

**Comment by richardanaya** [comment]
@jassler @Dhghomon @knightpp @albatraduce

**Comment by jassler** [comment]
Hey, minor note if it doesn't bother you too much, it would be nice having a little more meaningful commit messages other than "New Pages" :)

Was looking through the history of lessons.yaml [here](https://github.com/richardanaya/tour_of_rust/commits/master/lessons.yaml) and it's a little difficult pin-pointing specific commits.

**Comment by richardanaya** [comment]
Oh! Will do, sorry, I've just automated this with a script not aware people were looking at them :) will do

**Comment by knightpp** [comment]
Previously you used bold formatting to emphasis some parts, but in this page, you used '* *' an italic markdown formatting. Is that right?
[I'm talking about these lines](https://github.com/richardanaya/tour_of_rust/blob/master/lessons.yaml#L1170)

**Comment by richardanaya** [comment]
Great catch, updated
