### ISSUE TITLE
Add a darkmode

### ISSUE THREAD

**Issue by Zerotask** [richardanaya/tour_of_rust#387]
In my opinion it's much easier to read text with a dark background. Therefore we should add an option to simply switch to a darkmode.
This could be done with a simple icon, for example next to the headline.

### Example with the browser extension "Dark Reader"
![image](https://user-images.githubusercontent.com/20150243/117553071-95610300-b04f-11eb-9c9c-bfc3de61c679.png)

**Comment by richardanaya** [comment]
This sounds like a great idea that's simple to implement.  If you're interested in trying your hand at developing this, go ahead, if not i'll get to this eventually :)
