### ISSUE TITLE
Functions Page - incorrect terminology

### ISSUE THREAD

**Issue by richardanaya** [richardanaya/tour_of_rust#42]
https://tourofrust.com/05_en.html

https://github.com/richardanaya/tour_of_rust/commit/5ab68cf5939552690aa66ed05954896801d19b53

**Comment by richardanaya** [comment]
@jassler @Dhghomon @knightpp @albatraduce

**Comment by knightpp** [comment]
Did you mean https://tourofrust.com/03_en.html ?

**Comment by richardanaya** [comment]
Yes, sorry, I moved around two pages and it has messed up some links.

Awesome :)

**Comment by jassler** [comment]
If it was this commit, there's also nothing to do for German :)

fed1d9222eefb64481c18467cf74ce8d03b5c02d

**Comment by jassler** [comment]
Wait actually, that's not true. My bad
