### ISSUE TITLE
Code Panel Takes Very Little Vertical Space

### ISSUE THREAD

**Issue by kevin51jiang** [richardanaya/tour_of_rust#424]
On a normal 1080p screen, the code panel has a `max-height ` of `500px`  which makes it very hard to read the code after its run. Maybe it should be responsive to screen size?
![image](https://user-images.githubusercontent.com/33907581/145660777-9fbd2985-cca2-4a9b-91ea-382b867aa459.png)

**Comment by askor** [comment]
This is also true for mobile. In vertical rotation there is barely any space for the code.

![01F8B1DC-33A6-4F4E-9C72-FB14297BCBBB](https://user-images.githubusercontent.com/11080290/174061722-80154946-0548-4d61-934a-77168aab2c72.png)

Somewhat related is horizontal space when using a mobile device in horizontal rotation. The page doesn't fill the horizontal space:

![E4AC21B0-15C9-43C4-AB1B-008CB4C0A25C](https://user-images.githubusercontent.com/11080290/174061942-13e8ddbe-1c1f-4062-9be7-c07c490cc5c4.png)
