### ISSUE TITLE
Help with maintaining?

### ISSUE THREAD

**Issue by alexandruradovici** [richardanaya/tour_of_rust#500]
We love this project and use it a lot in teaching Rust.

We tried to submit several PR-us fixing typos and adding new translations, but there does not seem to be any activity for a few months. @richardanaya is there any way we can help with maintaining this repository? Thank you.

**Comment by richardanaya** [comment]
@alexandruradovici @Plaigeorge @aniakchak09 @mariapana @teodorobert @alx-sima @Adin3 @alcyone33 @Anda275 

Thank you all for your Romanian contributions! Sounds like you are learning a lot! I'll work to keep more responsive of Romanian PRs for you all. I did my best merging them all, apologies if I merged any in the wrong order.

**Comment by richardanaya** [comment]
Published to main site! 🚀
