### ISSUE TITLE
Cookie notice

### ISSUE THREAD

**Issue by Mubelotix** [richardanaya/tour_of_rust#525]
My friend @josselinonduty noticed you are using google analytics. That implies you are legally required to present a cookie notice. Or you can switch to a cookie-less alternative like Plausible or Simple Analytics.

**Comment by Mubelotix** [comment]
Not completed

**Comment by richardanaya** [comment]
@Mubelotix should be fixed now

**Comment by josselinonduty** [comment]
@Mubelotix fixed in f100817, lgtm
