### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by mgemard** [richardanaya/tour_of_rust#58]
I can do the french translation. Do you already have someone for it?

**Comment by richardanaya** [comment]
Awesome! we do not. :) welcome to the team. Let me know how I can help, you should just have to edit the single `lessons.yaml` file. No need to generate html or anything.

1. I'd start with translating some of the common words at the top of the file.
2. Maybe start slow and just do chapter 1 

Have a great day!

**Comment by richardanaya** [comment]
Closing this since we have the first chapter. We can go from PRs from here!
