### ISSUE TITLE
Do page generation in another branch

### ISSUE THREAD

**Issue by knightpp** [richardanaya/tour_of_rust#59]
Currently, all commits go in the master branch, but there is too much 'generating new html' commits.

I think it would be better if page generation would be split into another branch.
Perhaps `Makefile` would be like this
```
publish:
    git checkout pages
    // git rebase master // ?
    generate
    lint
    git add .
    git commit -m 'generating new html'
    git push
    git checkout master
```

**Comment by richardanaya** [comment]
Super interesting idea! I'll try it out

**Comment by richardanaya** [comment]
Nice :) I think I figured out a system with the `gh-pages` branch
