### ISSUE TITLE
discussion about immutability

### ISSUE THREAD

**Issue by mgemard** [richardanaya/tour_of_rust#63]
You say [here](https://tourofrust.com/04_en.html)

> * **immutable** - the location in memory can only be read

Infering that the location in memory can not be written.
Technicaly, this is not 100% correct:

> Immutability does not imply that the object as stored in the computer's memory is unwriteable. Rather, immutability is a compile-time construct that indicates what a programmer can do through the normal interface of the object, not necessarily what they can absolutely do (for instance, by circumventing the type system or violating const correctness in C or C++).

Taken from [Immutable object](https://en.wikipedia.org/wiki/Immutable_object) on wikipedia

I am not sure if this apply to rust though.

Just wanted to let you know.

**Comment by richardanaya** [comment]
Great point!

**Comment by richardanaya** [comment]
https://github.com/richardanaya/tour_of_rust/commit/ebb1d7363fab9cb3de80eeeaf279dc30c43cd6c1

**Comment by richardanaya** [comment]
I changed the phrasing, let me know what you think

**Comment by mgemard** [comment]
Sounds good.

In the french version I literally said:

* **mutable** - the variable can be modified and his value read
* **immutable** - only the value of the variable can be read
