### ISSUE TITLE
Split out returning from loop to it's own page

### ISSUE THREAD

**Issue by richardanaya** [richardanaya/tour_of_rust#66]
I split out returning from a loop to it's own page.

@jassler I might not have retained the correctness of the german version https://tourofrust.com/19_de.html

**Comment by jassler** [comment]
Hi,

sorry for the long silence, been feeling a little under the weather lately. I see there's been some huge updates! Hopefully I can keep up!

**Comment by richardanaya** [comment]
No worries at all @jassler hope you are doing well :) no rush
