### ISSUE TITLE
Tour of Web Assembly Chapter 1

### ISSUE THREAD

**Issue by richardanaya** [richardanaya/tour_of_rust#69]
Hey all, I started a new Tour of Web Assembly.  I know you all might not be interested in web tech, but if you are, feel free to contribute to `wasm.yaml`! 

https://tourofrust.com/webassembly

@jassler @Dhghomon @knightpp @albatraduce @Denstone @mgemard @spartucus

**Comment by Dhghomon** [comment]
Looks good! WASM is my weak point so nice to see this. Just submitted a PR with Occidental-Interlingue.
