### ISSUE TITLE
Question about generics

### ISSUE THREAD

**Issue by mgemard** [richardanaya/tour_of_rust#89]
In [What Are Generic Types?](https://tourofrust.com/33_en.html)

You say in a comment:

// Note: by using generic types here, we create compile-time created types
// making our code-size bigger. Turbofish let's us be explicit.

Did you mean `smaller` instead of `bigger`?

**Comment by mgemard** [comment]
@richardanaya

**Comment by richardanaya** [comment]
Great question, I think what I meant to imply is that the binary is potentially larger due to duplicate functions, but you are correct the code is more concise :P

**Comment by richardanaya** [comment]
Ah, I looked into this. This section is on generic structs, I can't even really talk about generic functions yet because ToR hasn't introduced traits yet.

I simply ended up with this comment

```
// Note: by using generic types here, we create compile-time created types. 
    // Turbofish let's us be explicit.
```
https://github.com/richardanaya/tour_of_rust/commit/cac0dd5edad5e770649902eff6e9c9edcd3368fe

**Comment by mgemard** [comment]
ok

your correction is already in the french version
